language: android
jdk: oraclejdk8


android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-x86-64-android-25

script:
    - /team_18-production/FinancialAdvisor/app./build.gradle
    - echo no | android create avd --force -n test -t android-25 --abi x86-64
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator