language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=x86-64

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-x86-64-android-25 

